stats/urls.py
from django.conf.urls import url

from . import views


app_name = 'stats'

urlpatterns = [
    url(
        r'^$',
        views.overview,
        name='overview'
    ),
]

tournament/urls.py
from django.conf.urls import url

from . import views

app_name = 'tournament'

urlpatterns = [
    url(
        r'^(?P<tournament_id>[0-9]+)/$',
        views.about,
        name='view'
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/rules/$',
        views.rules,
        name='rules'
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/prizes/$',
        views.prizes,
        name='prizes'
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/about/$',
        views.about,
        name='about'
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/groups/$',
        views.groups_view,
        name='groups'
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/calendar/$',
        views.calendar,
        name='calendar'
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/calendar-feed/$',
        views.calendar_feed,
        name='calendar_feed'
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/calendar/new-event/$',
        views.create_calendar_event,
        name='create_calendar_event'
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/about/edit/$',
        views.edit_about,
        name='edit_about'
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/games/$',
        views.games_view,
        name='games'
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/games/(?P<sgf_id>[0-9]+)$',
        views.games_view,
        name='games'
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/brackets/$',
        views.brackets_view,
        name='brackets'
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/players/$',
        views.players_view,
        name='players'
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/profile/(?P<user_id>[0-9]+)/update/$',
        views.edit_player_profile,
        name='edit_player_profile'
    ),
    url(
        r'^create/$',
        views.TournamentCreate.as_view(success_url='/tournament/list/'),
        name='create'
    ),
    url(
        r'^list/$',
        views.tournament_list,
        name='list'
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/calendar/manage/$',
        views.manage_calendar,
        name='manage_calendar'
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/admin/settings/$',
        views.manage_settings,
        name='manage_settings'
    ),

    url(
        r'^(?P<tournament_id>[0-9]+)/admin/groups/$',
        views.manage_groups,
        name='manage_groups'
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/admin/brackets/$',
        views.manage_brackets,
        name='manage_brackets'
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/admin/games/$',
        views.manage_games,
        name='manage_games'
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/admin/upload_sgf/$',
        views.upload_sgf,
        name='upload_sgf'
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/admin/create-sgf/$',
        views.create_sgf,
        name='create_sgf'
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/admin/set-stage/$',
        views.set_stage,
        name='set_stage'
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/admin/invite/$',
        views.invite_user,
        name='invite_user'
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/admin/quit/$',
        views.remove_players,
        name='remove_players'
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/save_players_order/$',
        views.save_players_order,
        name='save_players_order'
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/create-group/$',
        views.create_group,
        name='create_group'
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/create-bracket/$',
        views.create_bracket,
        name='create_bracket'
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/save-groups/$',
        views.save_groups,
        name='save_groups'
    ),
    url(
        r'^create-match/(?P<round_id>[0-9]+)/$',
        views.create_match,
        name='create_match'
    ),
    url(
        r'^delete_match/(?P<round_id>[0-9]+)/$',
        views.delete_match,
        name='delete_match'
    ),
    url(
        r'^create-round/(?P<bracket_id>[0-9]+)/$',
        views.create_round,
        name='create_round'
    ),
    url(
        r'^rename-round/(?P<round_id>[0-9]+)/$',
        views.rename_round,
        name='rename_round'
    ),
    url(
        r'^delete-round/(?P<round_id>[0-9]+)/$',
        views.delete_round,
        name='delete_round'
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/save-brackets/$',
        views.save_brackets,
        name='save_brackets'
    ),
    url(
        r'^rename-bracket/(?P<bracket_id>[0-9]+)/$',
        views.rename_bracket,
        name='rename_bracket'
    ),
    url(
        r'^delete-bracket/(?P<bracket_id>[0-9]+)/$',
        views.delete_bracket,
        name='delete_bracket'
    ),
    url(
        r'^update-event/(?P<pk>[0-9]+)/$',
        views.TournamentEventUpdate.as_view(),
        name='update_event'
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/set-winner/$',
        views.set_winner,
        name='set_winner'
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/forfeit_group/(?P<group_id>[0-9]+)/$',
        views.forfeit_group,
        name='forfeit_group'
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/forfeit_bracket/(?P<match_id>[0-9]+)/$',
        views.forfeit_bracket,
        name='forfeit_bracket'
    ),
]

tournament/forms.py
from django import forms
from django.forms import ModelForm
from league.models import Profile
from league.forms import ProfileForm
from .models import Tournament, TournamentGroup, Round

class TournamentForm(forms.ModelForm):
    class Meta:
        model = Tournament
        fields = [
            'name',
            'begin_time',
            'end_time',
            'tag',
            'clock_type',
            'main_time',
            'additional_time',
            'board_size',
            'komi',
            'is_open',
            'is_public',
            'use_calendar',
            'description',
            'ppwin',
            'pploss',
            'event_type',
        ]
        widgets = {
            'name': forms.TextInput(),
            'begin_time': forms.SelectDateWidget(),
            'end_time': forms.SelectDateWidget(),
            'ppwin': forms.HiddenInput(),
            'pploss': forms.HiddenInput(),
            'event_type': forms.HiddenInput(),
        }

class TournamentAboutForm(ModelForm):
    class Meta:
        model = Tournament
        fields = ['description', 'about', 'rules', 'prizes']

class TournamentPlayerProfileForm(ProfileForm):
    class Meta:
        model = Profile
        fields = ProfileForm.Meta.fields + ['picture_url']


class TournamentGroupForm(ModelForm):
    class Meta:
        model = TournamentGroup
        fields = ['name']

class RoundForm(ModelForm):
    class Meta:
        model = Round
        fields = ['name']

class ForfeitForm(forms.Form):
    winner = forms.IntegerField(label='user_id')
    looser = forms.IntegerField(label='user_id')
    next = forms.CharField(label='next', widget=forms.HiddenInput(), required=False)

tournament/views.py
from datetime import datetime
import json
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.template import loader
from django.shortcuts import get_object_or_404
from django.db.models.functions import Lower
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.decorators import user_passes_test, login_required
from django.contrib import messages
from django.urls import reverse
from django.utils import timezone
from league.models import User, Sgf
from league.forms import SgfAdminForm, ActionForm
from fullcalendar.forms import UTCPublicEventForm
from community.forms import CommunytyUserForm
from pytz import utc
from .models import Tournament, Bracket, Match, TournamentPlayer, TournamentGroup, Round, TournamentEvent
from .forms import TournamentForm, TournamentGroupForm, RoundForm, TournamentAboutForm,\
    TournamentPlayerProfileForm, ForfeitForm
from .utils import save_round


def rules(request, tournament_id):
    tournament = get_object_or_404(Tournament, pk=tournament_id)
    admin = request.user.is_authenticated and request.user.is_league_admin(tournament)
    groups = TournamentGroup.objects.filter(league_event=tournament).exists()

    context = {
        'tournament': tournament,
        'admin': admin,
        'groups': groups,
    }
    template = loader.get_template('tournament/rules.html')
    return HttpResponse(template.render(context, request))

def prizes(request, tournament_id):
    tournament = get_object_or_404(Tournament, pk=tournament_id)
    admin = request.user.is_authenticated and request.user.is_league_admin(tournament)
    groups = TournamentGroup.objects.filter(league_event=tournament).exists()

    context = {
        'tournament': tournament,
        'admin': admin,
        'groups': groups,
    }
    template = loader.get_template('tournament/prizes.html')
    return HttpResponse(template.render(context, request))

def about(request, tournament_id):
    tournament = get_object_or_404(Tournament, pk=tournament_id)
    admin = request.user.is_authenticated and request.user.is_league_admin(tournament)
    groups = TournamentGroup.objects.filter(league_event=tournament).exists()
    now = timezone.now()
    events = tournament.tournamentevent_set.filter(end__gte=now).order_by('start')

    context = {
        'tournament': tournament,
        'admin': admin,
        'groups': groups,
        'events': events
    }
    template = loader.get_template('tournament/about.html')
    return HttpResponse(template.render(context, request))

def brackets_view(request, tournament_id):
    tournament = get_object_or_404(Tournament, pk=tournament_id)
    groups = TournamentGroup.objects.filter(league_event=tournament).exists
    brackets = tournament.bracket_set.all()


    context = {
        'tournament': tournament,
        'groups': groups,
        'admin': request.user.is_authenticated and request.user.is_league_admin(tournament),
        'brackets': brackets
    }
    template = loader.get_template('tournament/brackets.html')
    return HttpResponse(template.render(context, request))

def groups_view(request, tournament_id):
    tournament = get_object_or_404(Tournament, pk=tournament_id)
    groups = TournamentGroup.objects.filter(league_event=tournament).order_by('order')

    for group in groups:
        results = group.get_results()
        group.results = results
    context = {
        'tournament': tournament,
        'groups': groups,
        'admin': request.user.is_authenticated and request.user.is_league_admin(tournament)
    }
    template = loader.get_template('tournament/groups.html')
    return HttpResponse(template.render(context, request))


def games_view(request, tournament_id, sgf_id=None):
    tournament = get_object_or_404(Tournament, pk=tournament_id)
    groups = TournamentGroup.objects.filter(league_event=tournament).exists()
    sgfs = tournament.sgf_set.only(
        'date',
        'black',
        'white',
        'winner',
        'result',
        'league_valid').filter(league_valid=True).\
        prefetch_related('white', 'black', 'winner').\
        select_related('white__profile', 'black__profile').\
        order_by('-date')
    context = {
        'sgfs': sgfs,
        'tournament': tournament,
        'groups': groups,
        'admin': request.user.is_authenticated and request.user.is_league_admin(tournament)
    }
    if sgf_id is not None:
        sgf = get_object_or_404(Sgf, pk=sgf_id)
        context.update({'sgf':sgf})
    template = loader.get_template('tournament/games.html')
    return HttpResponse(template.render(context, request))


def players_view(request, tournament_id):
    tournament = get_object_or_404(Tournament, pk=tournament_id)
    groups = TournamentGroup.objects.filter(league_event=tournament).exists()
    players = tournament.leagueplayer_set.order_by(Lower('user__username'))
    context = {
        'tournament': tournament,
        'players': players,
        'groups': groups,
        'admin': request.user.is_authenticated and request.user.is_league_admin(tournament)
    }
    template = loader.get_template('tournament/players.html')
    return HttpResponse(template.render(context, request))


def calendar(request, tournament_id):
    tournament = get_object_or_404(Tournament, pk=tournament_id)
    groups = TournamentGroup.objects.filter(league_event=tournament).exists

    context = {
        'tournament': tournament,
        'admin': request.user.is_authenticated and request.user.is_league_admin(tournament),
        'groups': groups,
        'user': request.user
    }
    template = loader.get_template('tournament/calendar.html')
    return HttpResponse(template.render(context, request))

def calendar_feed(request, tournament_id):
    """get all events for one user and serve a json."""

    tournament = get_object_or_404(Tournament, pk=tournament_id)
    user = request.user
    # get user timezone
    if user.is_authenticated:
        tz = user.get_timezone()
    else:
        tz = utc

    # Get start and end from request and use user tz
    start = datetime.strptime(request.GET.get('start'), '%Y-%m-%d')
    start = timezone.make_aware(start, tz)
    end = datetime.strptime(request.GET.get('end'), '%Y-%m-%d')
    end = timezone.make_aware(end, tz)

    data = tournament.get_formated_events(start, end, tz)
    return HttpResponse(json.dumps(data), content_type="application/json")
############################################################################
###                  Admin views                                         ###
############################################################################

class TournamentCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    """Create a tournament"""
    form_class = TournamentForm
    model = Tournament
    template_name_suffix = '_create_form'
    initial = {
        'begin_time': datetime.now(),
        'end_time': datetime.now(),
        'ppwin': 1,
        'pploss': 0,
        'event_type': 'tournament',
        }

    def test_func(self):
        return self.request.user.is_authenticated and \
            self.request.user.is_league_admin()

    def get_login_url(self):
        return '/'

class TournamentEventUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    form_class = UTCPublicEventForm
    model = TournamentEvent
    template_name_suffix = '_update_form'

    def test_func(self):
        return self.get_object().can_edit(self.request.user)

    def get_login_url(self):
        return '/'
    def get_success_url(self):
        return reverse(
            'tournament:manage_calendar',
            kwargs={'tournament_id': self.get_object().tournament.pk}
            )

@login_required()
def manage_calendar(request, tournament_id):
    tournament = get_object_or_404(Tournament, pk=tournament_id)
    if not request.user.is_league_admin(tournament):
        raise Http404('What are you doing here?')
    groups = TournamentGroup.objects.filter(league_event=tournament).exists
    events = tournament.tournamentevent_set.all()
    context = {
        'tournament': tournament,
        'events': events,
        'groups': groups
    }
    template = loader.get_template('tournament/manage_events.html')
    return HttpResponse(template.render(context, request))

@login_required()
def create_calendar_event(request, tournament_id):
    tournament = get_object_or_404(Tournament, pk=tournament_id)
    if not request.user.is_league_admin(tournament):
        raise Http404('What are you doing here?')
    if request.method == 'POST':
        form = UTCPublicEventForm(request.POST)
        if form.is_valid():
            event = TournamentEvent()
            event.start = form.cleaned_data['start']
            event.end = form.cleaned_data['end']
            event.description = form.cleaned_data['description']
            event.title = form.cleaned_data['title']
            event.url = form.cleaned_data['url']
            event.tournament = tournament
            event.save()
            message = "Succesfully created a tournament event."
            messages.success(request, message)
            return HttpResponseRedirect(reverse(
                'tournament:manage_calendar',
                kwargs={'tournament_id': tournament.pk}
            ))
    form = UTCPublicEventForm({
        'start': datetime.now(),
        'end': datetime.now()
    })
    context = {
        'tournament': tournament,
        'form': form
    }
    template = loader.get_template('tournament/create_calendar_event.html')
    return HttpResponse(template.render(context, request))

@login_required()
def edit_player_profile(request, tournament_id, user_id):
    tournament = get_object_or_404(Tournament, pk=tournament_id)
    user = get_object_or_404(User, pk=user_id)
    if not request.user.is_league_admin(tournament):

tournament/templates/tournament/includes/bracket_view.html
{% load bootstrap3 league_tags tournament_tags%}

{% for bracket in brackets %}
  <legend >
  {{bracket.name}}
  </legend>
  {% with bracket.get_rounds as rounds %}
  <div class=" bracket">
    {% for round in rounds %}
      <ul class="round">
        <li><legend >{{round.name}}</legend></li>
      </ul>
    {% endfor %}
  </div>
    <div class="bracket">

    {% for round in rounds %}
      <ul class="round">

        {% for match in round.get_matchs %}
        <li class="spacer">&nbsp;</li>
        <li class="panel panel-default match">
            <div class="panel-body match {% if match.sgf %} played {% endif %}"
                  id="match_{{match.pk}}"
                  data-match="{{match.pk}}"
                   data-round="{{round.pk}}"
                   data-bracket="{{bracket.pk}}">
                {% if match.player_1 %}
                <div
                  class="list-group-item
                  {% if match.winner and match.winner == match.player_1 %}list-group-item-success{% endif %}"
                  data-id="{{match.player_1.pk}}">
                  {% if match.player_1.user.profile.country %}
                  <img   src="{{match.player_1.user.profile.country.flag}}">
                  {% endif %}
                  {{match.player_1.user |user_link}}
                  {% if match.winner %}
                    {% if match.winner == match.player_1 %}
                    <span class="pull-right">
                      {% match_result %}
                    </span>
                    {% endif %}
                  {% elif admin %}
                  <span class="pull-right">
                  <form action="{% url 'tournament:forfeit_bracket' tournament.pk match.pk %}"  method="post" class="form">
                    {% csrf_token %}
                    <input id="winner" name="winner" type="hidden" value="{{match.player_2.pk}}">
                    <input id="looser" name="looser" type="hidden" value="{{match.player_1.pk}}">
                    <input id="next" name="next" type="hidden" value="{{request.path}}">
                    <button
                      type="submit"
                      class="btn btn-danger btn-xs"
                      onclick="return confirm('{{match.player_1.user.username}} declare forfeit ?')"
                      data-toggle="tooltip"
                      title="{{match.player_1.user.username}} forfeit this match"
                    >
                      F
                    </button>
                  </form>
                  </span>
                  {% endif %}

               </div>
                {% endif %}
                {% if match.player_2 %}
                <div
                  class="list-group-item {% if match.winner and match.winner == match.player_2 %}list-group-item-success{% endif %}"
                  data-id="{{match.player_2.pk}}">
                  {% if match.player_2.user.profile.country %}
                  <img   src="{{match.player_2.user.profile.country.flag}}">
                  {% endif %}
                  {{match.player_2.user |user_link}}
                  {% if match.winner %}
                    {% if match.winner == match.player_2 %}
                    <span class="pull-right">
                      {% match_result %}
                    </span>
                    {% endif %}
                  {% elif admin %}
                  <span class="pull-right">
                  <form action="{% url 'tournament:forfeit_bracket' tournament.pk match.pk %}"  method="post" class="form">
                    {% csrf_token %}
                    <input id="winner" name="winner" type="hidden" value="{{match.player_2.pk}}">
                    <input id="looser" name="looser" type="hidden" value="{{match.player_1.pk}}">
                    <input id="next" name="next" type="hidden" value="{{request.path}}">
                    <button
                      type="submit"
                      class="btn btn-danger btn-xs"
                      onclick="return confirm('{{match.player_1.user.username}} declare forfeit ?')"
                      data-toggle="tooltip"
                      title="{{match.player_1.user.username}} forfeit this match"
                    >
                      F
                    </button>
                  </form>
                  </span>
                  {% endif %}

                </div>

                {% endif %}

              </div>
            </li>

        {% endfor %}
        <li class="spacer">&nbsp;</li>
      </ul>


    {% endfor %}
  </div>

  {% endwith %}

{% endfor %}

tournament/templates/tournament/includes/event_list.html
{%load tz calendar_tags%}
{% get_current_timezone as TIME_ZONE %}

<ul class="sidebar">
  <h4>
  <a href="{% url 'tournament:calendar' tournament.pk%}">  <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
  Upcoming events ({{TIME_ZONE}})
</a>
  </h4>
{% get_now as now %}

{% for cal_event in events %}
  {% if cal_event.url %}  <a href="{{cal_event.url}}">    {% endif %}
<div class="panel cal-event-sidebar">

  <div class="panel-body">
    <div class="col-md-4">
      <p>
        {% if cal_event.start.date == now.date %}
        Today !
        {% else %}
        {{cal_event.start|date:"d, M"}}
        {% endif %}
      </p>

      <p>{{cal_event.start|time:"TIME_FORMAT"}}</p>

    </div>
    <div class="col-md-8" style="text-align: center;">
<div class=" label label-default cal-event-title">
      {{cal_event.title}}

    </div>
    <div class="text-center cal-event-description">
      {{cal_event.description}}

    </div>

    </div>
    {% if cal_event.url %}  </a>  {% endif %}
</div>
</div>

{% endfor %}


</ul>

tournament/templates/tournament/includes/group_results_manage.html
{% load league_tags %}
{% get_meijin as meijin %}

<div class='table-responsive'>
    <table id='example' class='table table-bordered  table-hover table-condensed' >
        <thead class='table-league-highlight'>
        <tr>
            <th>player</th>
            <th>score</th>
            {% for player in results %}
            <th>
                <div class="kgs_username">{{ player.user.username }}</div>
            </th>
            {% endfor %}
        </thead>
        <tbody>
        {% for player in results %}
        <tr  class="{% cycle 'even-row' 'odd-row' %}">
            <td class='table-league-player{%if not player.is_active %} inactive{%endif%}'  data-id={{player.pk}}>
              {{forloop.counter}}. {{player.user | user_link:meijin}}
            </td>
            <td class='table-league-score-highlight'>{{ player.score }}</td>
            {% for opponent in results %}

            {% if forloop.counter == forloop.parentloop.counter %}
            <td class="table-league-highlight {% cycle 'even-column' 'odd-column' %}">
                {% else %}
            <td class="{% cycle 'even-column' 'odd-column' %}">
              {% html_one_result %}
            </td>
            {% endif %}
            {% endfor %}
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

tournament/templates/tournament/includes/group_table.html
{% load tournament_tags league_tags bootstrap3%}
{% get_meijin as meijin %}

<div class='table-responsive'>
    <table id='example' class='table table-bordered  table-hover table-condensed' >
        <thead class='table-league-highlight'>
        <tr>
            <th>player</th>

            {% for player in results %}
            <th>
                <div class="kgs_username">{{ player.user.username }}</div>
            </th>
            {% endfor %}
            <th>score</th>
            <th>sos</th>
            <th>sodos</th>
            {% if admin %}
            <th>forfeit against</th>
            {% endif %}
        </thead>
        <tbody>
        {% for player in results %}
        <tr class="{% cycle 'even-row' 'odd-row' %}">
            <td class='table-league-player{%if not player.is_active %} inactive{%endif%}'>
              {{forloop.counter}}. {{player.user | user_link:meijin}}
            </td>
            {% for opponent in results %}

            {% if forloop.counter == forloop.parentloop.counter %}
            <td class="table-league-highlight {% cycle 'even-column' 'odd-column' %}">
                {% else %}
            <td class="{% cycle 'even-column' 'odd-column' %}">
              {% tourney_result %}
            </td>
            {% endif %}
            {% endfor %}
            <td class='table-league-score-highlight'>{{ player.score }}</td>

            <td>{{ player.sos }}</td>
            <td>{{ player.sodos }}</td>
            {% if admin %}
            <td>
              <form action="{% url 'tournament:forfeit_group' tournament.pk group.pk %}"  method="post" class="form">
                {% csrf_token %}
                <select name="winner">
                  {% for opponent in results %}
                  {% if forloop.counter != forloop.parentloop.counter %}
                  <option value="{{opponent.pk}}">{{opponent.user.username}}</option>
                  {% endif %}
                  {% endfor %}
                </select>
                <input id="looser" name="looser" type="hidden" value="{{player.pk}}">
                <input id="next" name="next" type="hidden" value="{{request.path}}">
                <button
                  type="submit"
                  class="btn btn-primary btn-xs"
                  onclick="return confirm('{{player.user.username}} declare forfeit ?')" >
                  {% bootstrap_icon "ok" %}
                </button>
              </form>

            </td>
            {% endif %}
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

tournament/templates/tournament/includes/manage_bracket.html
{% for rounds in bracket.rounds %}

tournament/templates/tournament/includes/manage_menu.html
<ul class="nav nav-tabs">
<li role="presentation" {% if active == 'settings'%}class="active"{% endif %}>
  <a href={%url 'tournament:manage_settings' tournament.pk %}>
    Settings & players
  </a>
</li>
<li role="presentation" {% if active == 'groups'%}class="active"{% endif %}>
  <a href={%url 'tournament:manage_groups' tournament.pk %}>
    Groups
  </a>
</li>
<li role="presentation" {% if active == 'brackets'%}class="active"{% endif %}>
  <a href={%url 'tournament:manage_brackets' tournament.pk %}>
  Brackets
</a>
</li>
<li role="presentation" {% if active == 'games'%}class="active"{% endif %}>
  <a href={%url 'tournament:manage_games' tournament.pk %}>
  Games
</a>
</li>
</ul>

tournament/templates/tournament/includes/tournament_menu.html
{% load bootstrap3 league_tags static forum_markup_tags%}
<div class="row">
<nav class="navbar navbar-default">
<ul class="nav navbar-nav navbar-left">
  <li {% if active == "about" %}class="active"{% endif %}>
    <a href="{% url "tournament:about" tournament.pk%}">About</a>
  </li>
  {% if groups %}
  <li {% if active == "groups" %}class="active"{% endif %}>
    <a href="{% url "tournament:groups" tournament.pk%}">Groups</a>
  </li>
  {% endif %}
  <li {% if active == "brackets" %}class="active"{% endif %}>
    <a href="{% url "tournament:brackets" tournament.pk%}">Brackets</a>
  </li>
  <li {% if active == "games" %}class="active"{% endif %}>
    <a href="{% url "tournament:games" tournament.pk%}">Games</a>
  </li>
  <li {% if active == "players" %}class="active"{% endif %}>
    <a href="{% url "tournament:players" tournament.pk%}">Players</a>
  </li>
  {% if tournament.use_calendar %}
  <li {% if active == "calendar" %}class="active"{% endif %}>
    <a href="{% url "tournament:calendar" tournament.pk%}">Calendar</a>
  </li>
  {% endif %}
  {% if tournament.rules %}
  <li {% if active == "rules" %}class="active"{% endif %}>
    <a href="{% url "tournament:rules" tournament.pk%}">Rules</a>
  </li>
  {% endif %}
  {% if tournament.prizes %}
  <li {% if active == "prizes" %}class="active"{% endif %}>
    <a href="{% url "tournament:prizes" tournament.pk%}">Prizes</a>
  </li>
  {% endif %}
</ul>
{% if admin %}
<ul class="nav navbar-nav navbar-right active" style="margin-right:5px;">
  <li>
    {% if active == "groups" %}
    <a href="{% url "tournament:manage_groups" tournament.pk%}">
    {% elif active == "brackets" %}
    <a href="{% url "tournament:manage_brackets" tournament.pk%}">
    {% elif active == "games" %}
    <a href="{% url "tournament:manage_brackets" tournament.pk%}">
    {% else %}
    <a href="{% url "tournament:manage_settings" tournament.pk%}">
    {% endif %}
      <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
    </a>
  </li>
</ul>
{% endif %}

</nav>
</div>