community/urls.py
from django.conf.urls import url

from . import views

app_name = 'community'

urlpatterns = [
    url(
        r'^(?P<slug>[\w.@+-]+)/$',
        views.community_page,
        name='community_page'
    ),
    url(
        r'^admin/list/$',
        views.admin_community_list,
        name='admin_community_list'
    ),
    url(
        r'^admin/create/$',
        views.admin_community_create,
        name='admin_community_create'
    ),
    url(
        r'^admin/delete/(?P<pk>[0-9]+)/$',
        views.admin_community_delete,
        name='admin_community_delete'
    ),
    url(
        r'^admin/update/(?P<pk>[0-9]+)/$',
        views.AdminCommunityUpdate.as_view(success_url='/community/admin/list/'),
        name='admin_community_update'
    ),
    url(
        r'^(?P<pk>[0-9]+)/users/$',
        views.admin_user_list,
        name='admin_user_list'
    ),
    url(
        r'^(?P<pk>[0-9]+)/invite/$',
        views.admin_invite_user,
        name='admin_invite_user'
    ),
    url(
        r'^update/(?P<pk>[0-9]+)/$',
        views.CommunityUpdate.as_view(),
        name='community_update'
    ),
    url(
        r'^(?P<community_pk>[0-9]+)/join/(?P<user_pk>[0-9]+)/$',
        views.community_join,
        name='community_join'
    ),
    url(
        r'^(?P<community_pk>[0-9]+)/quit/(?P<user_pk>[0-9]+)/$',
        views.community_quit,
        name='community_quit'
    ),
    url(
        r'^(?P<slug>[\w.@+-]+)/results/$',
        views.community_results_page,
        name='community_resutls'
    ),
    url(
        r'^$',
        views.community_list,
        name='community_list'
    ),
    url(
        r'^(?P<community_pk>[0-9]+)/league/create/$',
        views.CommunityLeagueEventCreate.as_view(),
        name='create_league'
    ),
    url(
        r'^league/(?P<pk>[0-9]+)/update/$',
        views.CommunityLeagueEventUpdate.as_view(),
        name='update_league'
    ),
    url(
        r'^(?P<community_pk>[0-9]+)/tournament/create/$',
        views.CommunityTournamentCreate.as_view(),
        name='create_tournament'
    ),
]

league/urls.py
from django.conf.urls import url

from . import views

app_name = 'league'
urlpatterns = [
    url(r'^$', views.division_results, name='results'),
    # Sad, but for historical reason, info page is named event.
    # If you want to replace reverses everywhere, be my guest
    url(r'^infos/$', views.infos, name='event'),

    url(r'^results/$', views.division_results, name='results'),
    url(r'^meijin/$', views.meijin, name='meijin'),
    url(r'^ladder/$', views.ladder, name='ladder'),
    url(r'^ddk/$', views.ddk, name='ddk'),
    url(r'^dan/$', views.dan, name='dan'),
    url(r'^admin/event/(?P<to_event_id>[0-9]+)/populate/$',
        views.populate, name='admin_event_populate'),
    url(r'^admin/event/(?P<to_event_id>[0-9]+)/populate/(?P<from_event_id>[0-9]+)/$',
        views.populate, name='admin_event_populate'),

    url(r'^admin/event/(?P<to_event_id>[0-9]+)/proceed-populate/(?P<from_event_id>[0-9]+)/$',
        views.proceed_populate, name='admin_proceed_populate'),
    url(r'^archives/$', views.archives, name='archives'),

    url(r'^(?P<event_id>[0-9]+)/results/(?P<division_id>[0-9]+)/$', views.division_results, name='results'),
    url(r'^(?P<event_id>[0-9]+)/results/$', views.division_results, name='results'),
    url(r'^(?P<event_id>[0-9]+)/$', views.division_results, name='results'),
    url(r'^(?P<event_id>[0-9]+)/infos/$', views.infos, name='event'),

    url(r'^games/$', views.list_games, name='games'),
    url(r'^games/(?P<sgf_id>[0-9]+)/$', views.list_games, name='game'),
    url(r'^(?P<event_id>[0-9]+)/games/$', views.list_games, name='games'),
    url(r'^(?P<event_id>[0-9]+)/games/(?P<sgf_id>[0-9]+)/$', views.list_games, name='game'),

    url(r'^players/$', views.list_players, name='players'),
    url(r'^(?P<event_id>[0-9]+)/players/$', views.list_players, name='players'),

    url(r'^discord/$', views.discord_redirect, name='discord_redirect'),

    url(r'^sgf/(?P<sgf_id>[0-9]+)/$', views.download_sgf, name='sgf'),
    url(r'^all_sgf/(?P<user_id>[0-9]+)/$', views.download_all_sgf, name='all_sgf'),

    url(r'^account/timezone/$', views.timezone_update, name='timezone_update'),


    url(r'^account/$', views.account, name='league_account'),
    url(r'^account/(?P<user_name>[\w.@+-]+)/$', views.account, name='league_account'),
    url(r'^scraper/$', views.scraper_view, name='scraper'),

    url(r'^admin/$', views.admin, name='admin'),
    url(r'^admin/sgf/(?P<sgf_id>[0-9]+)/$', views.admin_edit_sgf, name='edit_sgf'),
    url(r'^admin/handle-upload-sgf/$', views.handle_upload_sgf, name='handle_upload_sgf'),
    url(r'^admin/handle-upload-sgf/(?P<tournament_id>[0-9]+)/$', views.handle_upload_sgf, name='handle_upload_sgf'),
    url(r'^admin/upload-sgf/$', views.upload_sgf, name='upload_sgf'),
    url(r'^admin/create-sgf/$', views.create_sgf, name='create_sgf'),

    url(r'^admin/events/$', views.admin_events, name='admin_events'),
    url(
        r'^admin/events/(?P<pk>[0-9]+)/$',
        views.LeagueEventUpdate.as_view(),
        name='admin_events_update'
    ),
    url(
        r'^admin/events/create/$',
        views.LeagueEventCreate.as_view(success_url='/league/admin/events/'),
        name='admin_events_create'
    ),
    url(
        r'^admin/events/create/(?P<copy_from_pk>[0-9]+)/$',
        views.LeagueEventCreate.as_view(),
        name='admin_events_create'
    ),
    url(r'^admin/events/(?P<event_id>[0-9]+)/set_primary/$',
        views.admin_events_set_primary, name='set_primary'),
    url(r'^admin/events/(?P<event_id>[0-9]+)/delete/$',
        views.admin_events_delete, name='delete_event'),
    url(r'^admin/sgf/$', views.admin_sgf_list, name='admin_sgf'),
    url(r'^admin/sgf/(?P<sgf_id>[0-9]+)/save/$', views.admin_save_sgf, name='save_sgf'),
    url(r'^admin/sgf/(?P<sgf_id>[0-9]+)/delete/$', views.admin_delete_sgf, name='delete_sgf'),
    url(r'^admin/events/(?P<event_id>[0-9]+)/create-division/$',
        views.admin_create_division, name='admin_create_division'),
    url(r'^admin/division/(?P<division_id>[0-9]+)/delete-division/$',
        views.admin_delete_division, name='admin_delete_division'),
    url(r'^admin/division/(?P<division_id>[0-9]+)/rename/$',
        views.admin_rename_division, name='admin_rename_division'),
    url(r'^admin/division/(?P<division_id>[0-9]+)/winner/$',
        views.division_set_winner, name='division_set_winner'),
    url(r'^admin/division/(?P<division_id>[0-9]+)/up-down/$',
        views.admin_division_up_down, name='admin_division_up_down'),
    url(r'^admin/users/$', views.admin_users_list, name='admin_users_list'),
    url(r'^admin/users/event/(?P<event_id>[0-9]+)/$',
        views.admin_users_list, name='admin_users_list'),
    url(r'^admin/users/event/(?P<event_id>[0-9]+)/division/(?P<division_id>[0-9]+)/$',
        views.admin_users_list, name='admin_users_list'),
    url(r'^admin/users/(?P<user_id>[0-9]+)/send-mail/$',
        views.admin_user_send_mail, name='admin_user_send_mail'),
    url(r'^scrap-list/$', views.scrap_list, name='scrap_list'),
    url(r'^scrap-list/(?P<profile_id>[0-9]+)/up/$', views.scrap_list_up, name='scrap_list_up'),
    url(r'^game/json/(?P<sgf_id>[0-9]+)/$', views.game_api, name='game_api'),
    url(r'^game/json/(?P<sgf_id>[0-9]+)/(?P<event_id>[0-9]+)/$', views.game_api, name='game_api'),

    url(r'^(?P<event_id>[0-9]+)/join/(?P<user_id>[0-9]+)/$', views.join_event, name='join_event'),
    url(r'^(?P<event_id>[0-9]+)/quit/$', views.quit_league, name='quit_league'),
    url(r'^(?P<event_id>[0-9]+)/quit/(?P<user_id>[0-9]+)/$', views.quit_league, name='quit_league'),

    url(r'^admin/create-all-profiles/$', views.create_all_profiles, name='create_all_profiles'),
    url(r'^admin/update-all-sgf-check-code/$',
        views.update_all_sgf_check_code, name='update_all_sgf_check_code'),
    url(
        r'^admin/update_all_profile_ogs/$',
        views.update_all_profile_ogs,
        name='update_all_profile_ogs'
    ),
    url(r'^admin/set-meijin/$', views.admin_set_meijin, name='set_meijin'),
    url(
        r'^profile/(?P<pk>[0-9]+)/update$',
        views.ProfileUpdate.as_view(),
        name='profile_update'
    ),
    url(r'discord-api/$', views.discord_api, name='discord_api')
]

stats/urls.py
from django.conf.urls import url

from . import views


app_name = 'stats'

urlpatterns = [
    url(
        r'^$',
        views.overview,
        name='overview'
    ),
]

league/forms.py
import datetime

from django import forms
from django.contrib.auth.models import Group
from django.forms import ModelForm
from django_countries.widgets import CountrySelectWidget
import pytz

from .models import Division, LeagueEvent, Profile
from .ogs import get_user_id, get_user_rank


class SgfAdminForm(forms.Form):
    sgf = forms.CharField(label='sgf data', widget=forms.Textarea(attrs={'cols': 60, 'rows': 20}))
    url = forms.CharField(label="KGS archive link", required=False)

class ActionForm(forms.Form):
    action = forms.CharField(label='action', widget=forms.HiddenInput(), required=False)
    user_id = forms.IntegerField(label='user_id', widget=forms.HiddenInput(), required=False)
    next = forms.CharField(label='next', widget=forms.HiddenInput(), required=False)


class LeagueSignupForm(forms.Form):
    kgs_username = forms.CharField(max_length=10, required=False)
    ogs_username = forms.CharField(max_length=40, required=False)
    timezone = forms.ChoiceField(
        label='Time Zone',
        choices=[(t, t) for t in pytz.common_timezones],
        required=False,
        initial='UTC'
    )

    def clean_kgs_username(self):
        if not self.cleaned_data['kgs_username']:
            return ''
        kgs_username = self.cleaned_data['kgs_username']
        if Profile.objects.filter(kgs_username__iexact=kgs_username).exists():
            self.add_error('kgs_username', "This kgs username is already used by one of our member. You should contact us")
        return kgs_username

    def clean_ogs_username(self):
        # Check ogs username to be registered and update ogs_id
        if not self.cleaned_data['ogs_username']:
            return ''
        ogs_username = self.cleaned_data['ogs_username']
        if Profile.objects.filter(ogs_username__iexact=ogs_username).exists():
            self.add_error('ogs_username', 'Someone is already using this OGS username. Please contact an admin')
        id = get_user_id(ogs_username)
        if id == 0:
            self.add_error('ogs_username', 'There is no such user registered at the Online Go Server')
        return ogs_username

    def clean(self):
        super(LeagueSignupForm, self).clean()
        if not (self.cleaned_data['kgs_username'] or self.cleaned_data['ogs_username']):
            self.add_error('kgs_username', '')
            self.add_error('ogs_username', '')
            raise forms.ValidationError("You should enter OGS or KGS username")
        return self.cleaned_data

    def signup(self, request, user):
        user.kgs_username = self.cleaned_data['kgs_username']
        group = Group.objects.get(name='new_user')
        user.groups.add(group)
        user.save()
        profile = Profile(
            user=user,
            timezone=self.cleaned_data['timezone']
        )
        if self.cleaned_data['kgs_username']:
            profile.kgs_username = self.cleaned_data['kgs_username']
        if self.cleaned_data['ogs_username']:
            profile.ogs_username = self.cleaned_data['ogs_username']
            id = get_user_id(self.cleaned_data['ogs_username'])
            profile.ogs_id = id
            id = get_user_id(self.cleaned_data['ogs_username'])
            if id > 0:
                profile.ogs_rank = get_user_rank(id)
        profile.save()


class UploadFileForm(forms.Form):
    file = forms.FileField()

class LeaguePopulateForm(forms.Form):
    # a form related to a set of leagueplayers with one field per player.
    def __init__(self, from_event, to_event, *args, **kwargs):
        super(LeaguePopulateForm, self).__init__(*args, **kwargs)
        players = from_event.get_players()
        divisions = to_event.get_divisions()
        for player in players:
            choices = [(division.pk, division.name) for division in divisions] + [(0, 'drop')]
            self.fields['player_'+str(player.pk)] = forms.ChoiceField(choices=choices, required=False)
            # an attempt to set initial choice with same order... failed.
            #division =divisions.filter(order=player.division.order).first()
            #if division != None:
            #    self.fields['player_'+str(player.pk)].inital = (division.pk,division.name)

class DivisionForm(ModelForm):
    next = forms.CharField(label='next', widget=forms.HiddenInput(), required=False)
    class Meta:
        model = Division
        fields = ['name', 'next']


class LeagueEventForm(forms.ModelForm):
    class Meta:
        model = LeagueEvent
        fields = [
            'name',
            'event_type',
            'begin_time',
            'end_time',
            'nb_matchs',
            'ppwin',
            'pploss',
            'min_matchs',
            'tag',
            'board_size',
            'komi',
            'clock_type',
            'main_time',
            'additional_time',
            'is_open',
            'is_public',
            'description',
            'prizes'
        ]
        # Customise year list to show 2 years in the past/future
        EVENT_YEAR_CHOICES = range(datetime.date.today().year - 2, datetime.date.today().year + 3)
        widgets = {
            'name': forms.TextInput(),
            'begin_time': forms.SelectDateWidget(years=EVENT_YEAR_CHOICES),
            'end_time': forms.SelectDateWidget(years=EVENT_YEAR_CHOICES),
        }
        help_texts = {
            'name': "Name of the league",
            'event_type': 'League will work',
            'begin_time': "UTC time at 00:00.",
            'end_time': "Set it to the 1st to have full month.",
            'nb_matchs': 'Maximum number of match two players can play together',
            'ppwin': 'Point per win',
            'pploss': 'Point per loss',
            'min_matchs': 'Minimum of match for a user to be considered active',
            'is_open': 'Can people register and game get scraped?',
            'is_public': 'Can people see the league?',
        }

class EmailForm(forms.Form):
    subject = forms.CharField(required=True)
    copy_to = forms.CharField(required=False)
    message = forms.CharField(widget=forms.Textarea())


class TimezoneForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['timezone']

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = [
            'bio',
            'ogs_username',
            'kgs_username',
            'country',
            'go_quest_username'
        ]
        widgets = {'country': CountrySelectWidget()}

    def clean_kgs_username(self):
        if not self.cleaned_data['kgs_username']:
            return ''
        kgs_username = self.cleaned_data['kgs_username']
        if Profile.objects.filter(kgs_username__iexact=kgs_username).\
                exclude(pk=self.instance.pk).exists():
            self.add_error('kgs_username', 'Someone is already using this KGS username. Please contact an admin')
        else:  # Update all related league players kgs username
            open_players = self.instance.user.leagueplayer_set.filter(event__is_open=True)
            open_players.update(kgs_username=kgs_username)
        return kgs_username

    def clean_ogs_username(self):
        if not self.cleaned_data['ogs_username']:
            return ''
        # Check ogs username to be registered and update ogs_id
        ogs_username = self.cleaned_data['ogs_username']
        if ogs_username:
            id = get_user_id(ogs_username)
            if id == 0:
                self.add_error('ogs_username', 'There is no such user registered at the Online Go Server')
            elif Profile.objects.filter(ogs_username__iexact=ogs_username).\
                    exclude(pk=self.instance.pk).exists():
                self.add_error('ogs_username', 'Someone is already using this OGS username. Please contact an admin')
            else:
                # update ogs_id
                self.instance.ogs_id = id
                self.instance.save()
                # update all related players ogs usernames
                open_players = self.instance.user.leagueplayer_set.filter(event__is_open=True)
                open_players.update(ogs_username=ogs_username)
        return ogs_username

    def clean_go_quest_username(self):
        if not self.cleaned_data['go_quest_username']:
            return ''
        go_quest_username = self.cleaned_data['go_quest_username']
        if go_quest_username:
            if Profile.objects.filter(go_quest_username__iexact=go_quest_username).\
                    exclude(pk=self.instance.pk).exists():
                self.add_error(
                    'go_quest_username',
                    'Someone is already using this Go Quest username. Please contact an admin'
                )
            else:
                # udate goquest username for all players
                open_players = self.instance.user.leagueplayer_set.filter(event__is_open=True)
                open_players.update(go_quest_username=go_quest_username)
                print(open_players)
        return go_quest_username

    def clean(self):
        super(ProfileForm, self).clean()
        if not (self.cleaned_data['kgs_username'] or self.cleaned_data['ogs_username']):
            self.add_error('kgs_username', '')
            self.add_error('ogs_username', '')
            raise forms.ValidationError("You should enter OGS or KGS username")
        return self.cleaned_data

league/templates/league/admin/base.html
{% extends "full_width.html" %}

{% block title %}OSR league admin{% endblock %}

{%block page_intro %}
{% if request.user.is_league_admin %}
<div class="container">
<div class="row">
<nav class="navbar navbar-default">
<ul class="nav navbar-nav navbar-left">
  {% if request.user.is_osr_admin %}
  <li ><a href="{% url "league:admin" %}">Dashboard</a></li>
  <li ><a href="{% url "league:admin_users_list" %}">Users</a></li>
  <li ><a href="{% url "community:admin_community_list" %}">Communities</a></li>
  <li ><a href="{% url "calendar:admin_cal_event_list" %}">Events</a></li>
  {% endif %}
  <li ><a href="{% url "league:admin_events" %}">Leagues</a></li>
  <li ><a href="{% url "tournament:list" %}">Tournaments</a></li>
  <li ><a href="{% url "league:admin_sgf" %}">SGFs</a></li>
</ul>
</nav>
</div>
</div>

{% endif %}
{% endblock %}

league/templates/league/admin/create_all_profiles.html
{% extends "league/admin/base.html" %}
{% load wagtailcore_tags %}
{% load league_tags %}
{% load bootstrap3 %}

{% block title %}Update all sgfs{% endblock %}
{% block heading %}
<div class="page-header">
    <h1>Create all profiles</h1>
</div>
{%endblock%}
{% block content %}
<div class="row">
  <div class="jumbotron">
<p>Dear admin.</p>
<p> Please pay attention to this message and don't proceed before reading</p>
<p>In this page, you will create a profile for all users that don't have one. </p>
<p>If you don't understand what this is about, you should just leave this page. </p>
<p> If you have any doubt what so ever about wether you should continue or not, you should leave this page.</p>
  </div>
  <div class="col-md-4">
    <a href="{% url 'league:admin' %}"class="btn btn-primary text-left">Back to admin</a>
  </div>
  <div class="col-md-4">
  <form action=" {% url 'league:create_all_profiles'  %}" method="post" class="form">
{% csrf_token %}
<input type="hidden" name="action" value="create_all_profiles">
<button type="submit" class="btn btn-danger"  onclick="return confirm('Are you positively sure you want to create all profiles ?')">

{% bootstrap_icon "warning-sign" %} No fear, I do it !
</button>

</form>
</div>
{% endblock %}

league/templates/league/admin/event_list.html
{% load community_tags %}
<table id='events-table' class='display table' cellspacing='0' width='100%' >
	<thead>
	<tr>
		<th>Status</th>
		<th>Public?</th>
		<th>Name</th>
		<th>Begin</th>
		<th>End</th>
    <th>Community</th>
		<th>Players</th>
		<th>#Divisions</th>
		<th>#Games</th>
		<th>ppw</th>
		<th>ppl</th>
		<th>min match</th>
    <th>copy</th>

	</thead>
	<tbody>
	{% for event in events %}
	<tr {% if event.community is not None%} class="info"{% endif %}>
		<td> {% if event.is_open %} <b>Open</b> {% else %} Closed {% endif %}</td>
		<td>{% if event.is_public %} public {% else %} Private {% endif %}</td>
		<td> <a href= "{% url 'league:admin_events_update' event.pk %}"> {{ event.name }} </a> </td>
		<td> {{ event.begin_time | date:"M d, Y" }}  </td>
		<td> {{ event.end_time | date:"M d, Y" }} </td>
    <td>{{ event.community | community_link }}</td>
		<td><a href="{% url 'league:admin_users_list' event.pk %}">	{{ event.number_players }} </a></td>
		<td> {{ event.number_divisions }}</td>
		<td> {{ event.number_games }} </td>
		<td> {{ event.ppwin }} </td>
		<td> {{ event.pploss }} </td>
		<td> {{ event.min_matchs }} </td>
    <td> <a href= "{% url 'league:admin_events_create' event.pk %}"> <i class="fa fa-copy"></i> </a> </td

	</tr>
	{% endfor %}
	</tbody>
</table>

league/templates/league/admin/sgf_edit.html
{% extends "league/admin/base.html" %}
{% load bootstrap3 wgo_tags league_tags%}
{% block title %}Edit a sgf{% endblock %}

{% block heading %}
<div class="page-header">
    <h1>{{sgf.wplayer}} vs {{sgf.bplayer}} the {{sgf.date |date:"M d, Y"}}</h1>
</div>
{%endblock%}
{% block content %}

<div class="row">
  <div class="col-md-4">
    <p>
    <button form="sgf-form" type="submit" class="btn btn-info " formaction="{%url 'league:edit_sgf' sgf.pk%}" >
      {% bootstrap_icon "refresh" %}  Check sgf
    </button>
  </p>
  </div>
  <div class="col-md-4">
    <form  method="post" class="form">
    {% csrf_token %}
    <input type="hidden" name="action" value="delete_sgf">
    <button form="sgf-form" type="submit" class="btn btn-danger " formaction="{%url 'league:delete_sgf' sgf.pk%}" onclick="return confirm('Are you sure you want to delete this SGF ?')" >
      {% bootstrap_icon "remove" %}  Delete SGF
    </button>
    </form>
    </div>
</div>
{% if preview %}
<div class="row">
<div class="alert alert-info" role="alert">This is a preview of your changes. Click <button form="sgf-form" type="submit" class="btn btn-success btn-xs" formaction="{%url 'league:save_sgf' sgf.pk%}"onclick="return confirm('Save the sgf to db ?')" >
  {% bootstrap_icon "ok" %} Save sgf
</button> to save them to the database.</div>
</div>
{% endif %}
<div class="row">

   <div class="col-md-3">
     <div class="panel panel-default">
       <div class="panel-heading"> Sgf infos</div>
     <table class="table table-condensed">
    <tbody>
      <tr>
        <th>ID</th>
        <td> {{sgf.pk}}</td>
      </tr>
        <tr>
          <th>White</th>
            <td>{{sgf.wplayer}}</td>
        </tr>
        <tr>
          <th>Black</th>
            <td>{{sgf.bplayer}}</td>
        </tr>
        <tr>
          <th>Date</th>
          <td> {{sgf.date |date:"M d, Y"}}</td>
        </tr>
        <tr>
          <th>Result</th>
          <td> {{sgf.result}}</td>
        </tr>
        <tr>
          <th>Type</th>
          <td> {{sgf.game_type}}</td>
        </tr>
        <tr>
          <th>p_status</th>
          <td> {{sgf.p_status | p_status}}</td>
        </tr>
        <tr>
          <th>Download </th>
          <td>   <a href="{% url 'league:sgf' sgf.pk%}">{% bootstrap_icon 'save' %} </a></td>
        </tr>


      </tbody>
    </table>
</div>
<div class="panel panel-default">

  <div class="panel-heading">
{% if sgf.league_valid %}
     This SGF is valid for those events:
   </div>
   <table class="table table-condensed">
     {% for event in valid_events %}
     <tr><td>{{event | event_link}}</td></tr>
     {% endfor %}
{% else %}
This SGF is not valid :


</div>
<table class="table table-condensed">
{% with sgf.get_messages as messages %}
{% for message in messages %}
<tr><td>{{message}}</td></tr>
{% endfor %}
{% endwith %}
{% endif %}
</table>

   </div>


</div>





<div class="col-md-4">
  <form id="sgf-form"  method="post" class="form">
  {% csrf_token %}
    {% bootstrap_form form %}

  </form>




</div>
<div class="col-md-5">
  <div data-wgo="{{ sgf.sgf_text  | prepare_sgf}}">
</div>
</div>
</div>

{% endblock %}

league/templates/league/admin/sgf_list.html
{% extends 'league/admin/base.html' %}
{% load bootstrap3 league_tags%}
{% block heading %}
<div class="page-header">
    <h1>All sgfs</h1>
</div>
{%endblock%}

{% block content %}
<div class="panel panel-default">
  <div class="panel-heading">
    Upload a sgf
  </div>
  <div class="panel-body">
    <form enctype="multipart/form-data" class="form-inline"action=" {% url 'league:handle_upload_sgf' %}" method="post" class="form">
  {% csrf_token %}
  <div class="form-group"><label class="sr-only" for="id_file">File</label><div class="row bootstrap3-multi-input"><div class="col-xs-12"><input class="" id="id_file" name="file" title="" type="file" required /></div></div></div>
  <button type="submit" class="btn btn-success btn-sm" >
    {% bootstrap_icon "ok" %}  Submit
  </button>
  </form>
  </div>
</div>
<div class="panel panel-default">
  <div class="panel-heading">
    List of all OSR sgfs
  </div>
<table id='sgf-table' class='table table-over' >
  <thead>
    <th>Id</th>
    <th> Date</th>
    <th> White</th>
    <th>BLack</th>
    <th>Result</th>
    <th> Type </th>
    <th>League valid?</th>
    <th>p_status</th>
    <th>Edit</th>
  </thead>
</tbody>
{% for sgf in sgfs%}
<tr>
<td>{{sgf.pk}}</td>
<td>{{sgf.date | date:"M d, Y"}}</td>
<td>{{sgf.wplayer}}</td>
<td>{{sgf.bplayer}}</td>
<td>{{sgf.result}}</td>
<td>{{sgf.game_type}}</td>
<td>{{sgf.league_valid | boolean_icon}}</td>
<td>{{sgf.p_status}}</td>
<td><a href= "{% url 'league:edit_sgf' sgf.pk %}"> <span class="glyphicon glyphicon-menu-right"></span></a></td>

</tr>
  {% endfor %}
</tbody>
</table>
</div>
</div>

{% endblock %}

{% block extra_js %}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs/dt-1.10.16/datatables.min.css"/>
<script type="text/javascript" src="https://cdn.datatables.net/v/bs/dt-1.10.16/datatables.min.js"></script>
<script type="text/javascript">
$(document).ready(function() {
$('#sgf-table').DataTable({"order": [[ 0, "desc" ]]});
} );
</script>
{% endblock %}

league/templates/league/admin/user_send_mail.html
{% extends 'league/admin/base.html' %}
{% load bootstrap3 league_tags%}
{% block title %}OSR league admin - send mail{% endblock %}
{% block heading %}
<div class="page-header">
    <h1>Send an email to {{user}}</h1>
</div>
{%endblock%}
{% block content %}

<form action="{% url 'league:admin_user_send_mail' user.pk %}"  method="post" class="form">
{% csrf_token %}
  {% bootstrap_form form %}
  <button  type="submit" class="btn btn-primary" onclick="return confirm('Send this email to {{user}} ?')" >
    {% bootstrap_icon "send" %} Send mail
  </button>
</form>


{% endblock %}