league/urls.py
from django.conf.urls import url

from . import views

app_name = 'league'
urlpatterns = [
    url(r'^$', views.division_results, name='results'),
    # Sad, but for historical reason, info page is named event.
    # If you want to replace reverses everywhere, be my guest
    url(r'^infos/$', views.infos, name='event'),

    url(r'^results/$', views.division_results, name='results'),
    url(r'^meijin/$', views.meijin, name='meijin'),
    url(r'^ladder/$', views.ladder, name='ladder'),
    url(r'^ddk/$', views.ddk, name='ddk'),
    url(r'^dan/$', views.dan, name='dan'),
    url(r'^admin/event/(?P<to_event_id>[0-9]+)/populate/$',
        views.populate, name='admin_event_populate'),
    url(r'^admin/event/(?P<to_event_id>[0-9]+)/populate/(?P<from_event_id>[0-9]+)/$',
        views.populate, name='admin_event_populate'),

    url(r'^admin/event/(?P<to_event_id>[0-9]+)/proceed-populate/(?P<from_event_id>[0-9]+)/$',
        views.proceed_populate, name='admin_proceed_populate'),
    url(r'^archives/$', views.archives, name='archives'),

    url(r'^(?P<event_id>[0-9]+)/results/(?P<division_id>[0-9]+)/$', views.division_results, name='results'),
    url(r'^(?P<event_id>[0-9]+)/results/$', views.division_results, name='results'),
    url(r'^(?P<event_id>[0-9]+)/$', views.division_results, name='results'),
    url(r'^(?P<event_id>[0-9]+)/infos/$', views.infos, name='event'),

    url(r'^games/$', views.list_games, name='games'),
    url(r'^games/(?P<sgf_id>[0-9]+)/$', views.list_games, name='game'),
    url(r'^(?P<event_id>[0-9]+)/games/$', views.list_games, name='games'),
    url(r'^(?P<event_id>[0-9]+)/games/(?P<sgf_id>[0-9]+)/$', views.list_games, name='game'),

    url(r'^players/$', views.list_players, name='players'),
    url(r'^(?P<event_id>[0-9]+)/players/$', views.list_players, name='players'),

    url(r'^discord/$', views.discord_redirect, name='discord_redirect'),

    url(r'^sgf/(?P<sgf_id>[0-9]+)/$', views.download_sgf, name='sgf'),
    url(r'^all_sgf/(?P<user_id>[0-9]+)/$', views.download_all_sgf, name='all_sgf'),

    url(r'^account/timezone/$', views.timezone_update, name='timezone_update'),


    url(r'^account/$', views.account, name='league_account'),
    url(r'^account/(?P<user_name>[\w.@+-]+)/$', views.account, name='league_account'),
    url(r'^scraper/$', views.scraper_view, name='scraper'),

    url(r'^admin/$', views.admin, name='admin'),
    url(r'^admin/sgf/(?P<sgf_id>[0-9]+)/$', views.admin_edit_sgf, name='edit_sgf'),
    url(r'^admin/handle-upload-sgf/$', views.handle_upload_sgf, name='handle_upload_sgf'),
    url(r'^admin/handle-upload-sgf/(?P<tournament_id>[0-9]+)/$', views.handle_upload_sgf, name='handle_upload_sgf'),
    url(r'^admin/upload-sgf/$', views.upload_sgf, name='upload_sgf'),
    url(r'^admin/create-sgf/$', views.create_sgf, name='create_sgf'),

    url(r'^admin/events/$', views.admin_events, name='admin_events'),
    url(
        r'^admin/events/(?P<pk>[0-9]+)/$',
        views.LeagueEventUpdate.as_view(),
        name='admin_events_update'
    ),
    url(
        r'^admin/events/create/$',
        views.LeagueEventCreate.as_view(success_url='/league/admin/events/'),
        name='admin_events_create'
    ),
    url(
        r'^admin/events/create/(?P<copy_from_pk>[0-9]+)/$',
        views.LeagueEventCreate.as_view(),
        name='admin_events_create'
    ),
    url(r'^admin/events/(?P<event_id>[0-9]+)/set_primary/$',
        views.admin_events_set_primary, name='set_primary'),
    url(r'^admin/events/(?P<event_id>[0-9]+)/delete/$',
        views.admin_events_delete, name='delete_event'),
    url(r'^admin/sgf/$', views.admin_sgf_list, name='admin_sgf'),
    url(r'^admin/sgf/(?P<sgf_id>[0-9]+)/save/$', views.admin_save_sgf, name='save_sgf'),
    url(r'^admin/sgf/(?P<sgf_id>[0-9]+)/delete/$', views.admin_delete_sgf, name='delete_sgf'),
    url(r'^admin/events/(?P<event_id>[0-9]+)/create-division/$',
        views.admin_create_division, name='admin_create_division'),
    url(r'^admin/division/(?P<division_id>[0-9]+)/delete-division/$',
        views.admin_delete_division, name='admin_delete_division'),
    url(r'^admin/division/(?P<division_id>[0-9]+)/rename/$',
        views.admin_rename_division, name='admin_rename_division'),
    url(r'^admin/division/(?P<division_id>[0-9]+)/winner/$',
        views.division_set_winner, name='division_set_winner'),
    url(r'^admin/division/(?P<division_id>[0-9]+)/up-down/$',
        views.admin_division_up_down, name='admin_division_up_down'),
    url(r'^admin/users/$', views.admin_users_list, name='admin_users_list'),
    url(r'^admin/users/event/(?P<event_id>[0-9]+)/$',
        views.admin_users_list, name='admin_users_list'),
    url(r'^admin/users/event/(?P<event_id>[0-9]+)/division/(?P<division_id>[0-9]+)/$',
        views.admin_users_list, name='admin_users_list'),
    url(r'^admin/users/(?P<user_id>[0-9]+)/send-mail/$',
        views.admin_user_send_mail, name='admin_user_send_mail'),
    url(r'^scrap-list/$', views.scrap_list, name='scrap_list'),
    url(r'^scrap-list/(?P<profile_id>[0-9]+)/up/$', views.scrap_list_up, name='scrap_list_up'),
    url(r'^game/json/(?P<sgf_id>[0-9]+)/$', views.game_api, name='game_api'),
    url(r'^game/json/(?P<sgf_id>[0-9]+)/(?P<event_id>[0-9]+)/$', views.game_api, name='game_api'),

    url(r'^(?P<event_id>[0-9]+)/join/(?P<user_id>[0-9]+)/$', views.join_event, name='join_event'),
    url(r'^(?P<event_id>[0-9]+)/quit/$', views.quit_league, name='quit_league'),
    url(r'^(?P<event_id>[0-9]+)/quit/(?P<user_id>[0-9]+)/$', views.quit_league, name='quit_league'),

    url(r'^admin/create-all-profiles/$', views.create_all_profiles, name='create_all_profiles'),
    url(r'^admin/update-all-sgf-check-code/$',
        views.update_all_sgf_check_code, name='update_all_sgf_check_code'),
    url(
        r'^admin/update_all_profile_ogs/$',
        views.update_all_profile_ogs,
        name='update_all_profile_ogs'
    ),
    url(r'^admin/set-meijin/$', views.admin_set_meijin, name='set_meijin'),
    url(
        r'^profile/(?P<pk>[0-9]+)/update$',
        views.ProfileUpdate.as_view(),
        name='profile_update'
    ),
    url(r'discord-api/$', views.discord_api, name='discord_api')
]

stats/urls.py
from django.conf.urls import url

from . import views


app_name = 'stats'

urlpatterns = [
    url(
        r'^$',
        views.overview,
        name='overview'
    ),
]

league/forms.py
import datetime

from django import forms
from django.contrib.auth.models import Group
from django.forms import ModelForm
from django_countries.widgets import CountrySelectWidget
import pytz

from .models import Division, LeagueEvent, Profile
from .ogs import get_user_id, get_user_rank


class SgfAdminForm(forms.Form):
    sgf = forms.CharField(label='sgf data', widget=forms.Textarea(attrs={'cols': 60, 'rows': 20}))
    url = forms.CharField(label="KGS archive link", required=False)

class ActionForm(forms.Form):
    action = forms.CharField(label='action', widget=forms.HiddenInput(), required=False)
    user_id = forms.IntegerField(label='user_id', widget=forms.HiddenInput(), required=False)
    next = forms.CharField(label='next', widget=forms.HiddenInput(), required=False)


class LeagueSignupForm(forms.Form):
    kgs_username = forms.CharField(max_length=10, required=False)
    ogs_username = forms.CharField(max_length=40, required=False)
    timezone = forms.ChoiceField(
        label='Time Zone',
        choices=[(t, t) for t in pytz.common_timezones],
        required=False,
        initial='UTC'
    )

    def clean_kgs_username(self):
        if not self.cleaned_data['kgs_username']:
            return ''
        kgs_username = self.cleaned_data['kgs_username']
        if Profile.objects.filter(kgs_username__iexact=kgs_username).exists():
            self.add_error('kgs_username', "This kgs username is already used by one of our member. You should contact us")
        return kgs_username

    def clean_ogs_username(self):
        # Check ogs username to be registered and update ogs_id
        if not self.cleaned_data['ogs_username']:
            return ''
        ogs_username = self.cleaned_data['ogs_username']
        if Profile.objects.filter(ogs_username__iexact=ogs_username).exists():
            self.add_error('ogs_username', 'Someone is already using this OGS username. Please contact an admin')
        id = get_user_id(ogs_username)
        if id == 0:
            self.add_error('ogs_username', 'There is no such user registered at the Online Go Server')
        return ogs_username

    def clean(self):
        super(LeagueSignupForm, self).clean()
        if not (self.cleaned_data['kgs_username'] or self.cleaned_data['ogs_username']):
            self.add_error('kgs_username', '')
            self.add_error('ogs_username', '')
            raise forms.ValidationError("You should enter OGS or KGS username")
        return self.cleaned_data

    def signup(self, request, user):
        user.kgs_username = self.cleaned_data['kgs_username']
        group = Group.objects.get(name='new_user')
        user.groups.add(group)
        user.save()
        profile = Profile(
            user=user,
            timezone=self.cleaned_data['timezone']
        )
        if self.cleaned_data['kgs_username']:
            profile.kgs_username = self.cleaned_data['kgs_username']
        if self.cleaned_data['ogs_username']:
            profile.ogs_username = self.cleaned_data['ogs_username']
            id = get_user_id(self.cleaned_data['ogs_username'])
            profile.ogs_id = id
            id = get_user_id(self.cleaned_data['ogs_username'])
            if id > 0:
                profile.ogs_rank = get_user_rank(id)
        profile.save()


class UploadFileForm(forms.Form):
    file = forms.FileField()

class LeaguePopulateForm(forms.Form):
    # a form related to a set of leagueplayers with one field per player.
    def __init__(self, from_event, to_event, *args, **kwargs):
        super(LeaguePopulateForm, self).__init__(*args, **kwargs)
        players = from_event.get_players()
        divisions = to_event.get_divisions()
        for player in players:
            choices = [(division.pk, division.name) for division in divisions] + [(0, 'drop')]
            self.fields['player_'+str(player.pk)] = forms.ChoiceField(choices=choices, required=False)
            # an attempt to set initial choice with same order... failed.
            #division =divisions.filter(order=player.division.order).first()
            #if division != None:
            #    self.fields['player_'+str(player.pk)].inital = (division.pk,division.name)

class DivisionForm(ModelForm):
    next = forms.CharField(label='next', widget=forms.HiddenInput(), required=False)
    class Meta:
        model = Division
        fields = ['name', 'next']


class LeagueEventForm(forms.ModelForm):
    class Meta:
        model = LeagueEvent
        fields = [
            'name',
            'event_type',
            'begin_time',
            'end_time',
            'nb_matchs',
            'ppwin',
            'pploss',
            'min_matchs',
            'tag',
            'board_size',
            'komi',
            'clock_type',
            'main_time',
            'additional_time',
            'is_open',
            'is_public',
            'description',
            'prizes'
        ]
        # Customise year list to show 2 years in the past/future
        EVENT_YEAR_CHOICES = range(datetime.date.today().year - 2, datetime.date.today().year + 3)
        widgets = {
            'name': forms.TextInput(),
            'begin_time': forms.SelectDateWidget(years=EVENT_YEAR_CHOICES),
            'end_time': forms.SelectDateWidget(years=EVENT_YEAR_CHOICES),
        }
        help_texts = {
            'name': "Name of the league",
            'event_type': 'League will work',
            'begin_time': "UTC time at 00:00.",
            'end_time': "Set it to the 1st to have full month.",
            'nb_matchs': 'Maximum number of match two players can play together',
            'ppwin': 'Point per win',
            'pploss': 'Point per loss',
            'min_matchs': 'Minimum of match for a user to be considered active',
            'is_open': 'Can people register and game get scraped?',
            'is_public': 'Can people see the league?',
        }

class EmailForm(forms.Form):
    subject = forms.CharField(required=True)
    copy_to = forms.CharField(required=False)
    message = forms.CharField(widget=forms.Textarea())


class TimezoneForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['timezone']

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = [
            'bio',
            'ogs_username',
            'kgs_username',
            'country',
            'go_quest_username'
        ]
        widgets = {'country': CountrySelectWidget()}

    def clean_kgs_username(self):
        if not self.cleaned_data['kgs_username']:
            return ''
        kgs_username = self.cleaned_data['kgs_username']
        if Profile.objects.filter(kgs_username__iexact=kgs_username).\
                exclude(pk=self.instance.pk).exists():
            self.add_error('kgs_username', 'Someone is already using this KGS username. Please contact an admin')
        else:  # Update all related league players kgs username
            open_players = self.instance.user.leagueplayer_set.filter(event__is_open=True)
            open_players.update(kgs_username=kgs_username)
        return kgs_username

    def clean_ogs_username(self):
        if not self.cleaned_data['ogs_username']:
            return ''
        # Check ogs username to be registered and update ogs_id
        ogs_username = self.cleaned_data['ogs_username']
        if ogs_username:
            id = get_user_id(ogs_username)
            if id == 0:
                self.add_error('ogs_username', 'There is no such user registered at the Online Go Server')
            elif Profile.objects.filter(ogs_username__iexact=ogs_username).\
                    exclude(pk=self.instance.pk).exists():
                self.add_error('ogs_username', 'Someone is already using this OGS username. Please contact an admin')
            else:
                # update ogs_id
                self.instance.ogs_id = id
                self.instance.save()
                # update all related players ogs usernames
                open_players = self.instance.user.leagueplayer_set.filter(event__is_open=True)
                open_players.update(ogs_username=ogs_username)
        return ogs_username

    def clean_go_quest_username(self):
        if not self.cleaned_data['go_quest_username']:
            return ''
        go_quest_username = self.cleaned_data['go_quest_username']
        if go_quest_username:
            if Profile.objects.filter(go_quest_username__iexact=go_quest_username).\
                    exclude(pk=self.instance.pk).exists():
                self.add_error(
                    'go_quest_username',
                    'Someone is already using this Go Quest username. Please contact an admin'
                )
            else:
                # udate goquest username for all players
                open_players = self.instance.user.leagueplayer_set.filter(event__is_open=True)
                open_players.update(go_quest_username=go_quest_username)
                print(open_players)
        return go_quest_username

    def clean(self):
        super(ProfileForm, self).clean()
        if not (self.cleaned_data['kgs_username'] or self.cleaned_data['ogs_username']):
            self.add_error('kgs_username', '')
            self.add_error('ogs_username', '')
            raise forms.ValidationError("You should enter OGS or KGS username")
        return self.cleaned_data

league/templates/league/archive.html
{% extends "league/base.html" %}
{% load league_tags %}
{% block title %}OSR league - Archives{% endblock %}
{% block content %}
<ul class="nav nav-tabs">
  <li class="active"><a href="{% url 'league:archives' %}">Archives</a></li>
  {% for ev in open_events %}
  <li>
    {{ev|event_link}}
  </li>
  {% endfor %}
  <li class="pull-right"><a href="{% url 'league:scrap_list' %}">Scrap list</a></li>
  </ul>
<nav class="navbar navbar-default">
<ul class="nav navbar-nav navbar-left">
  <li class="active"><a href="{% url 'league:archives' %}">Leagues</a></li>
  <li><a href="{% url 'league:players'  %}">Players</a></li>
  <li><a href="{% url 'league:games'  %}">Games</a></li>
</ul>
</nav>
<div class="well"> This table show all leagues (past and present) of the Open Study Room. Open leagues are green.</div>
<table class='table'  >
   <thead>
     <tr>
       <th>Begin time</th>
       <th>End time</th>
       <th>Name</th>
       <th>Type</th>
       <th># Divisions</th>
       <th># Players</th>
       <th># games </th>
    </tr>
  </thead>
  <tbody>
    {% for event in  events %}
      <tr {% if event.is_open %}class="success"{%endif%}>
        <td>{{event.begin_time |date:"SHORT_DATE_FORMAT"}}</td>
        <td>{{event.end_time |date:"SHORT_DATE_FORMAT"}}</td>
        <td>
          {{event |event_link}}
           {% if  not event.is_public %}
          <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
            {% endif %}
        </td>
        <td>{{event.event_type}}</td>
        <td>{{ event.number_divisions }}</td>
        <td>{{event.number_players}}</td>
        <td>{{ event.number_games}}</td>
        <td></td>
      </tr>
    {% endfor %}
  </tbody>
</table>


{% endblock %}}

league/templates/league/archives_games.html
{% extends "league/base.html" %}
{% load league_tags wgo_tags l10n i18n%}

{% block title %}Archives - Games {% if sgf %}- {{sgf.black.username}} vs {{sgf.white.username}} {%endif %}{% endblock %}
{% block extra_head_js %}
<script type="text/javascript">
function load_game(sgf_id) {
  var url = "/league/game/json/" + sgf_id

  $.ajax({
    type: "GET",
    url: "/league/game/json/" + sgf_id,
    dataType: "json",
    success: processData,
    error: function(){ alert("failed"); }
});

function processData(data)
{
    document.getElementById("game_infos").innerHTML= data.game_infos ;
    var elem = document.getElementById("player");
    var player = new WGo.BasicPlayer(elem, {
      sgf: data.sgf
      });
    window.history.pushState('page2', 'Title', data.permalink);
    document.getElementById("game-header").innerHTML= ' - ' + data.white + ' vs ' + data.black;
    document.title ='Archives - Games - '+ data.white + ' vs ' + data.black + ' - Open Study Room';
};
return false;};
</script>
{% endblock %}
{% block content %}
{% language 'en' %}
<ul class="nav nav-tabs">
  <li class="active"><a href="{% url 'league:archives' %}">Archives</a></li>
  {% for ev in open_events %}
  <li>
    <a href="{% url 'league:games' ev.pk %}">{{ev}}</a>
  </li>
  {% endfor %}
  <li class="pull-right"><a href="{% url 'league:scrap_list' %}">Scrap list</a></li>
  </ul>
<nav class="navbar navbar-default">
<ul class="nav navbar-nav navbar-left">
  <li><a href="{% url 'league:archives' %}">Leagues</a></li>
  <li><a href="{% url 'league:players'  %}">Players</a></li>
  <li class="active"><a href="{% url 'league:games'  %}">Games</a></li>
</ul>
</nav>
<div class="well"> This table shows all games that have been played in the Open Study Room</div>

<div class ="row">
<div class="col-md-4">
  <div id ="game_infos">
    {% if sgf %}
  {% include "league/includes/game_info.html"  %}
    {% endif %}
</div>
<div class="panel panel-default">
<div class="panel-heading">Games</div>
{% include "league/includes/games.html" with sgfs=sgfs %}
</div>
</div>

<div class="col-md-8">
  {% if sgf %}
  <div id="player" data-wgo="{{ sgf.sgf_text | prepare_sgf}}" >
    </div>
    {% else %}
    <div id="player">
      <div class="alert alert-info">
      Click a game result to see it.
    </div>
    </div>
  {% endif %}
</div>
</div>
  {%endlanguage%}
{% endblock %}


{% block extra_js %}

<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs/dt-1.10.16/datatables.min.css"/>
<script type="text/javascript" src="https://cdn.datatables.net/v/bs/dt-1.10.16/datatables.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/plug-ins/1.10.13/dataRender/datetime.js"></script>

<script type="text/javascript">
$(document).ready(function() {
$('#game-table').DataTable({
  "bLengthChange": false ,"dom":'<"H"lr>ft<"F"ip>',
  "columnDefs": [ {
    targets: 0,
    render: $.fn.dataTable.render.moment( 'MMM DD, YYYY','MMM DD, YYYY' )
  } ],
  "order": [[ 0, "desc" ]]

});
} );
</script>

{% endblock %}

league/templates/league/base.html
{% extends "full_width.html" %}
{% load static community_tags forum_markup_tags%}
{% block heading%}
  <div class="page-header">
      <h1>{% if event.community %}{{event.community|community_link}}{%else%}OSR{%endif%} League - {%if event %}{{event}}{% else%}Archives{% endif %}<span id='game-header'>{%if game %} - {{game.black.kgs_username}} vs {{game.white.kgs_username}} {%endif%} </span></h1>
      {% if event.description %}{{event.description|safe|rendered}}{% endif %}
  </div>
  {%endblock%}
  {% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/league.css' %}"/>
  {% endblock %}

league/templates/league/leagueevent_update_form.html
{% extends 'league/admin/base.html' %}

{% load bootstrap3 league_tags tz%}

{% block title %}OSR league admin - Leagues{% endblock %}



{% block heading %}
<div class="page-header">
    <h1>Edit League "{{ object.name }}"</h1>
</div>
{%endblock%}
{% block content %}
{% timezone "UTC" %}
<div class="row">
  {% if object.number_players == 0 and object.number_divisions > 0%}
  <div class="alert alert-info clearfix">
    <div class=pull-left>
    <h4>Populate empty event</h4>

    This event has no player in it. You can populate it easily from a previous event :
    </div>
    <div>
    <form action="" method="GET" class="form-inline pull-right">
      <div class="form-group">
      <button type="submit" class="btn btn-primary" formaction="{% url 'league:admin_event_populate' object.pk %}">

        Populate this event
      </button>
       <label class="control-label">from</label>
      <select class="form-control" name="from_event" >
        {% for event in other_events %}
  <option value="{{event.pk}}">{{event}}</option>
  {% endfor %}
</select>
    </div>
    </form>
  </div>
  </div>
  {% endif %}

<div class="col-md-4">
  <legend>Edit {{object}} </legend>
<form action="" method="POST">{% csrf_token %}
	{% bootstrap_form form %}
	{% bootstrap_button "Save" button_type="submit" button_class="btn-primary" %}
</form>
{% if request.user.is_league_admin %}
<form action="" method="POST">{% csrf_token %}
<input type="hidden" name="action" value="set_primary">
<button type="submit" formaction="{% url 'league:set_primary' object.pk %}" class="btn btn-primary btn-xs pull-right">
  Set as primary
</button>
</form>
{% endif %}

<form action="{% url 'league:delete_event' object.pk %}" method="POST">{% csrf_token %}
	<input type="hidden" name="action" value="delete_event" />
	<button type="submit" class="btn btn-danger btn-xs pull-right"  onclick="return confirm('Are you sure you want to delete this Event?')">
		Delete
	</button>
</form>

</div>
<div class="col-md-8">
  <legend>{{object}} divisions</legend>
  <div class="panel panel-default">
    <div class="panel-heading"> Create a new division</div>
    <div class="panel-body">
  <form action="" method="POST" class="form-inline" >{% csrf_token %}
  <input type="hidden" name="next" value="{{request.path}}">
  <input id="name" class="form-control" name="name" placeholder="New division name" title=""  type="text">
  <button type="submit" formaction="{% url 'league:admin_create_division' object.pk %}" class="btn btn-primary  pull-right">
    {% bootstrap_icon "plus" %} Create new division
  </button>
  </form>
   </div>
 </div>
  {% for division in object.get_divisions %}
  <div class="panel panel-default">
    <div class="panel-heading clearfix">
<b>{{division.name}}</b>
       <div class="pull-right">
          <a href="{% url 'league:admin_users_list' object.pk division.pk %}">{{division.number_players}} players </a>| {{division.number_games}} games</div>
     </div>
    <div class="panel-body">
      <div class="row">
      <div class="col-md-6">
      <form action="" method="POST" class="form-inline" >{% csrf_token %}
        <input type="hidden" name="next" value="{{request.path}}">
        <input id="name" class="form-control" name="name" placeholder="Division name" value="{{division.name}}" title=""  type="text">
      <button type="submit" formaction="{% url 'league:admin_rename_division' division.pk %}" class="btn btn-primary">
  Rename
</button>
</form>
</div>
<div class="col-md-4">
      <form action="" method="POST" class="form-inline" >{% csrf_token %}
        <input type="hidden" name="action" value="delete_division">
        <input type="hidden" name="next" value="{{request.path}}">
        <button type="submit" formaction="{% url 'league:admin_delete_division' division.pk %}" class="btn btn-danger"
        onclick="return confirm('Delete the {% if division.number_players > 0 %}division {{division}} and all its players/games?'{% else %}empty division {{division}}?'{% endif %} )">
          {% bootstrap_icon "remove" %} Delete
        </button>
      </form>
    </div>
    <div class="col-md-1">
      {% if not division.is_first %}
      <form action="" method="POST" class="form-inline" >{% csrf_token %}
        <input type="hidden" name="action" value="division_up">
        <input type="hidden" name="next" value="{{request.path}}">
        <button type="submit" formaction="{% url 'league:admin_division_up_down' division.pk %}" class="btn btn-primary">
          {% bootstrap_icon "arrow-up" %}
        </button>
      </form>
      {% endif %}
    </div>
    <div class="col-md-1">
      {% if not division.is_last %}
      <form action="" method="POST" class="form-inline" >{% csrf_token %}
        <input type="hidden" name="action" value="division_down">
        <input type="hidden" name="next" value="{{request.path}}">
        <button type="submit" formaction="{% url 'league:admin_division_up_down' division.pk %}" class="btn btn-primary">
          {% bootstrap_icon "arrow-down" %}
        </button>
      </form>
      {% endif %}
    </div>

  </div>
</div>

    <div class="panel-footer">

    <form action="" method="POST" class="form-inline" >{% csrf_token %}
        <label for="user_id">Winner
          <select class="form-control" id="user_id" name="user_id">
            <option value="-1">-------------</option>
            {% for player in division.get_players %}
            <option value="{{player.user.pk}}" {%if division.winner == player.user%}selected {%endif%}>
              {{player.user.username}}
            </option>
            {% endfor %}
          </select>
        </label>
        <input type="hidden" name="next" value="{{request.path}}">
        <button type="submit" formaction="{% url 'league:division_set_winner' division.pk %}" class="btn btn-primary">
          <i class="fa fa-trophy"></i>
        </button>
    </form>
    </div>
  </div>

  {% endfor %}
</div>
</div>
{% endtimezone %}
{% endblock %}


{% block extra_css %}
    {{ form.media.css }}
{% endblock extra_css %}

{% block extra_js %}
{{ form.media.js }}

{% endblock extra_js %}