community/urls.py
from django.conf.urls import url

from . import views

app_name = 'community'

urlpatterns = [
    url(
        r'^(?P<slug>[\w.@+-]+)/$',
        views.community_page,
        name='community_page'
    ),
    url(
        r'^admin/list/$',
        views.admin_community_list,
        name='admin_community_list'
    ),
    url(
        r'^admin/create/$',
        views.admin_community_create,
        name='admin_community_create'
    ),
    url(
        r'^admin/delete/(?P<pk>[0-9]+)/$',
        views.admin_community_delete,
        name='admin_community_delete'
    ),
    url(
        r'^admin/update/(?P<pk>[0-9]+)/$',
        views.AdminCommunityUpdate.as_view(success_url='/community/admin/list/'),
        name='admin_community_update'
    ),
    url(
        r'^(?P<pk>[0-9]+)/users/$',
        views.admin_user_list,
        name='admin_user_list'
    ),
    url(
        r'^(?P<pk>[0-9]+)/invite/$',
        views.admin_invite_user,
        name='admin_invite_user'
    ),
    url(
        r'^update/(?P<pk>[0-9]+)/$',
        views.CommunityUpdate.as_view(),
        name='community_update'
    ),
    url(
        r'^(?P<community_pk>[0-9]+)/join/(?P<user_pk>[0-9]+)/$',
        views.community_join,
        name='community_join'
    ),
    url(
        r'^(?P<community_pk>[0-9]+)/quit/(?P<user_pk>[0-9]+)/$',
        views.community_quit,
        name='community_quit'
    ),
    url(
        r'^(?P<slug>[\w.@+-]+)/results/$',
        views.community_results_page,
        name='community_resutls'
    ),
    url(
        r'^$',
        views.community_list,
        name='community_list'
    ),
    url(
        r'^(?P<community_pk>[0-9]+)/league/create/$',
        views.CommunityLeagueEventCreate.as_view(),
        name='create_league'
    ),
    url(
        r'^league/(?P<pk>[0-9]+)/update/$',
        views.CommunityLeagueEventUpdate.as_view(),
        name='update_league'
    ),
    url(
        r'^(?P<community_pk>[0-9]+)/tournament/create/$',
        views.CommunityTournamentCreate.as_view(),
        name='create_tournament'
    ),
]

stats/urls.py
from django.conf.urls import url

from . import views


app_name = 'stats'

urlpatterns = [
    url(
        r'^$',
        views.overview,
        name='overview'
    ),
]

community/models.py
from django.db import models
from django.contrib.auth.models import Group
from django.contrib.auth import get_user_model
from machina.models.fields import MarkupTextField
from machina.core import validators

class Community(models.Model):

    name = models.CharField(max_length=20, blank=True, unique=True)
    slug = models.CharField(max_length=5, blank=True, unique=True)
    admin_group = models.ForeignKey(Group, related_name='admin_community', on_delete=models.CASCADE)
    user_group = models.ForeignKey(Group, null=True, blank=True, related_name='user_community', on_delete=models.CASCADE)
    close = models.BooleanField(default=False)
    private = models.BooleanField(default=False)
    promote = models.BooleanField(default=False)
    description = MarkupTextField(
        blank=True, null=True,
        validators=[validators.NullableMaxLengthValidator(2000)])
    private_description = MarkupTextField(
        blank=True, null=True,
        validators=[validators.NullableMaxLengthValidator(2000)])


    def __str__(self):
        return self.name

    @classmethod
    def create(cls, name, slug):
        '''We create the admin and users group before creating the community object'''

        if not Group.objects.filter(name=slug + '_community_admin').exists():
            admin_group = Group.objects.create(name=slug + '_community_admin')

        if not Group.objects.filter(name=slug + '_community_member').exists():
            user_group = Group.objects.create(name=slug + '_community_member')

        # else we should return an error:'group already here'
        community = cls(
            name=name,
            slug=slug,
            admin_group=admin_group,
            user_group=user_group
        )
        return community

    def get_admins(self):
        User = get_user_model()
        return list(User.objects.filter(groups=self.admin_group))

    def is_admin(self, user):
        admin = user.is_authenticated and (
            user.is_league_admin() or
            self.admin_group in user.groups.all()
        )
        return admin

    def is_member(self, user):
        return user in self.user_group.user_set.all()

community/forms.py
from django import forms
from django.forms import ModelForm

from league.models import User

from .models import Community

class AdminCommunityForm(ModelForm):
    class Meta:
        model = Community
        fields = ['name',
        'slug',
        'description',
        'private_description',
        'close',
        'private',
        'promote'
        ]

class CommunityForm(ModelForm):
    class Meta:
        model = Community
        fields = [
        'description',
        'private_description',
        'close',
        'private'
        ]

class CommunytyUserForm(forms.Form):
    username = forms.CharField(label='username')

    def clean_username(self):
        username = self.cleaned_data['username']
        if not User.objects.filter(username__iexact=username).exists():
            message = "We don't have a user with username" + username + "."
            raise forms.ValidationError(message)
        return username

community/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, Http404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic.edit import UpdateView
from django.urls import reverse
from django.contrib.auth.decorators import user_passes_test, login_required
from django.contrib import messages
from django.db.models import Q

from league.models import User, LeagueEvent, Sgf
from league.views import LeagueEventCreate, LeagueEventUpdate
from tournament.views import TournamentCreate
from .models import Community
from .forms import CommunityForm, AdminCommunityForm, CommunytyUserForm

@login_required()
@user_passes_test(User.is_osr_admin, login_url="/", redirect_field_name=None)
def admin_community_list(request):
    communitys = Community.objects.all()
    return render(request, 'community/admin/community_list.html', {'communitys': communitys})

@login_required()
@user_passes_test(User.is_osr_admin, login_url="/", redirect_field_name=None)
def admin_community_create(request):
    if request.method == 'POST':
        form = AdminCommunityForm(request.POST)
        if form.is_valid():
            community = Community.create(
                form.cleaned_data['name'],
                form.cleaned_data['slug']
            )
            community.save()
            return HttpResponseRedirect(reverse('community:admin_community_list'))
    else:
        form = AdminCommunityForm
        return render(request, 'community/admin/community_create.html', {'form': form})


class AdminCommunityUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    form_class = AdminCommunityForm
    model = Community
    template_name_suffix = '_admin_update'

    def test_func(self):
        user = self.request.user
        return user.is_authenticated and user.is_osr_admin()

    def get_login_url(self):
        return '/'


class CommunityUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    form_class = CommunityForm
    model = Community
    template_name_suffix = '_update'

    def get_success_url(self):
        return reverse(
            'community:community_page',
            kwargs={'slug': self.get_object().slug}
        )

    def test_func(self):
        user = self.request.user
        return self.get_object().is_admin(user)

    def get_login_url(self):
        return '/'


@login_required()
@user_passes_test(User.is_osr_admin, login_url="/", redirect_field_name=None)
def admin_community_delete(request, pk):
    community = get_object_or_404(Community, pk=pk)
    if request.method == 'POST':
        admin_group = community.admin_group
        user_group = community.user_group
        community.delete()
        admin_group.delete()
        if user_group is not None:
            user_group.delete()
        return HttpResponseRedirect(reverse('community:admin_community_list'))

    else:
        raise Http404('What are you doing here?')


def community_page(request, slug):
    community = get_object_or_404(Community, slug=slug)
    if community.private and not community.is_member(request.user):
        raise Http404('What are you doing here?')
    leagues = community.leagueevent_set.all()
    tournaments = leagues.filter(event_type='tournament')
    leagues = leagues.exclude(event_type='tournament')
    admin = community.is_admin(request.user)
    if not admin:
        leagues = leagues.filter(is_public=True)
    sgfs = Sgf.objects.filter(league_valid=True, events__in=leagues).order_by('-date')

    can_join = request.user.is_authenticated and \
        request.user.is_league_member() and \
        not community.is_member(request.user) and \
        not community.close

    context = {
        'community': community,
        'leagues': leagues,
        'tournaments': tournaments,
        'sgfs': sgfs,
        'admin': community.is_admin(request.user),
        'can_join': can_join,
        'can_quit': community.user_group in request.user.groups.all()
    }
    return render(request, 'community/community_page.html', context)

def community_list(request):
    groups = request.user.groups.all()
    communitys = Community.objects.filter(Q(private=False)|Q(user_group__in=groups))
    return render(
        request,
        'community/community_list.html',
        {'communitys': communitys}
    )

@login_required()
@user_passes_test(User.is_league_member, login_url="/", redirect_field_name=None)
def community_join(request, community_pk, user_pk):
    community = get_object_or_404(Community, pk=community_pk)
    user = get_object_or_404(User, pk=user_pk)
    if not community.is_admin(request.user) and (
        not user == request.user or community.close
    ):
        raise Http404('what are you doing here')

    if request.method == 'POST':
        user.groups.add(community.user_group)
        message = "You just join the " + community.name + " community."
        messages.success(request, message)
        return HttpResponseRedirect(reverse(
            'community:community_page',
            kwargs={'slug': community.slug}
        ))
    else:
        raise Http404('what are you doing here ?')

@login_required()
@user_passes_test(User.is_league_member, login_url="/", redirect_field_name=None)
def community_quit(request, community_pk, user_pk):
    community = get_object_or_404(Community, pk=community_pk)
    user = get_object_or_404(User, pk=user_pk)
    if not community.is_admin(request.user) and user != request.user:
        raise Http404('what are you doing here')
    if request.method == 'POST':
        user.groups.remove(community.user_group)
        if user == request.user:
            message = "You just quit the " + community.name + " community."
            messages.success(request, message)
            if community.private:
                return HttpResponseRedirect(reverse(
                    'community:community_list',
                ))
            else:
                return HttpResponseRedirect(reverse(
                    'community:community_page',
                    kwargs={'slug': community.slug}
                ))
        else:
            message = user.username + " is not in your community anymore."
            messages.success(request, message)
            return HttpResponseRedirect(reverse(
                'community:admin_user_list',
                kwargs={'pk': community.pk}
            ))
    else:
        raise Http404('what are you doing here ?')


def community_results_page(request, slug):
    """Redirect to the last community open league results page"""
    community = get_object_or_404(Community, slug=slug)
    league = LeagueEvent.objects.filter(
        community=community,
        is_open=True
    ).order_by('end_time').first()
    return HttpResponseRedirect(reverse(
        'league:results',
        kwargs={'event_id': league.pk})
    )


@login_required()
def admin_user_list(request, pk):
    """allow admin to manage the users of a community. Usefull for close ones."""
    community = get_object_or_404(Community, pk=pk)
    if not community.is_admin(request.user):
        raise Http404('what are you doing here')
    community_users = User.objects.filter(groups=community.user_group)
    return render(
        request,
        'community/admin/user_list.html',
        {'community': community, 'community_users': community_users}
    )

@login_required()
def admin_invite_user(request, pk):
    """Invite a user in a community."""
    community = get_object_or_404(Community, pk=pk)
    if not community.is_admin(request.user):
        raise Http404('what are you doing here')
    if request.method == 'POST':
        form = CommunytyUserForm(request.POST)
        if form.is_valid():
            user = User.objects.get(username__iexact=form.cleaned_data['username'])
            user.groups.add(community.user_group)
            # group = Group.objects.get(name='league_member')/
            # user.groups.add(group)
            message = user.username +" is now a member of your community."
            messages.success(request, message)
        else:
            message = "We don't have such a user."
            messages.success(request, message)
        return HttpResponseRedirect(reverse(
            'community:admin_user_list',
            kwargs={'pk': community.pk}
        ))


class CommunityLeagueEventCreate(LeagueEventCreate):
    """subclass of LeagueEventCreate view for communitys"""

    def test_func(self):
        community_pk = self.kwargs.get('community_pk')
        community = get_object_or_404(Community, pk=community_pk)
        return community.is_admin(self.request.user)

    def get_success_url(self):
        community_pk = self.kwargs.get('community_pk')
        community = get_object_or_404(Community, pk=community_pk)
        return reverse(
                'community:community_page',
                kwargs={'slug': community.slug}
        )

    def form_valid(self, form):
        response = super(CommunityLeagueEventCreate, self).form_valid(form)
        community_pk = self.kwargs.get('community_pk')
        community = get_object_or_404(Community, pk=community_pk)
        self.object.community = community
        self.object.save()
        return response

class CommunityLeagueEventUpdate(LeagueEventUpdate):
    def get_success_url(self):
        print("here")
        return reverse(
            'community:community_page',
            kwargs={'slug': self.get_object().community.slug}
        )

    def get_context_data(self, **kwargs):
        context = super(CommunityLeagueEventUpdate, self).get_context_data(**kwargs)
        league = self.get_object()
        context['other_events'] = league.get_other_events().filter(community=league.community)
        return context


class CommunityTournamentCreate(TournamentCreate):
    """subclass of TournamentCreate view for communitys"""
    def test_func(self):
        community_pk = self.kwargs.get('community_pk')

community/templates/community/admin/community_create.html
{% extends 'league/admin/base.html' %}
{% load bootstrap3 league_tags%}
{% block heading %}
<div class="page-header">
    <h1> Create a new Guest Community</h1>
</div>
{%endblock%}
{% block content %}
<form action="" method="POST">{% csrf_token %}
{%bootstrap_form form %}
	{% bootstrap_button "Save" button_type="submit" button_class="btn-primary" %}
</form>

{% endblock %}
{% block extra_css %}
    {{ form.media.css }}
{% endblock extra_css %}

{% block extra_js %}
{{ form.media.js }}
{% endblock extra_js %}

community/templates/community/admin/community_list.html
{% extends 'league/admin/base.html' %}
{% load bootstrap3 league_tags%}
{% block heading %}
<div class="page-header">
    <h1>Guest Communitys</h1>
</div>
{%endblock%}
{% block content %}

<div class="panel panel-default">

<div class="panel-heading">
    <h3>List of Communitys
        <a href= "{% url 'community:admin_community_create' %}">
            <button class="btn btn-success pull-right clearfix">
                {%bootstrap_icon 'plus'%} Create new community
            </button>
        </a>
    </h3>
</div>
<div class="panel-body">
    <table id='community-table' class='table table-over' >
      <thead>
        <th>Name</th>
        <th>Close</th>
        <th>Private</th>
        <th>Admins</th>
        <th>Edit</th>
        <th>Delete</th>
      </thead>
    <tbody>
    {% for community in communitys%}
        <tr>
            <td><a href="{% url 'community:community_page' community.slug %}">{{ community.name}}</a></td>
            <td>{{community.close}}</td>
            <td>{{community.private}}</td>
            <td>
                {% for user in community.get_admins %}
                    {{user|user_link}},
                {% endfor %}
            </td>
            <td>
                <a href="{% url 'community:admin_community_update' community.pk %}">
                    {% bootstrap_icon 'wrench' %}
                </a>
            </td>
            <td><form action="{% url 'community:admin_community_delete' community.pk %}" method="POST">
                  {% csrf_token %}
                    	<input type="hidden" name="action" value="delete_community" />
                    	<button type="submit" class="btn btn-danger btn-xs "  onclick="return confirm('Are you sure you want to delete this community?')">
                    	{% bootstrap_icon 'remove-circle' %} Delete
                    	</button>
                    </form>
            </td>
        </tr>
    {%endfor%}
    </tbody>
</table>
</div>
</div>



{% endblock %}

community/templates/community/admin/user_list.html
{% extends 'full_width.html' %}
{% load bootstrap3 league_tags community_tags%}
{% block heading %}
<div class="page-header">
       <h1> {{community|community_link}} members</h1>
</div>
{%endblock%}
{% block content %}
<div class="panel panel-default">
  <div class="panel-heading">
    Invite a user
  </div>
  <div class="panel-body">
    <form action=" {% url 'community:admin_invite_user' community.pk %}" method="post" >
        {% csrf_token %}
        <div class="form-group">
        <input type="text" name="username" placeholder="Username" >

        <button type="submit" class="btn btn-success btn-sm"  >
        {% bootstrap_icon "ok" %} Invite  !
        </button>
        </div>
        </form>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    All {{community.name}} members
  </div>
<table id="user-table" class="table">
  <thead>
    <th>Username</th>
    <th>KGS username</th>
    <th>kick out</th>
  </thead>
  <tbody>
{% for user in community_users %}
<tr>
  <td>{{user.username}}</td>
  <td>{{user |user_link}}</td>
  <td>  <form action=" {% url 'community:community_quit' community.pk user.pk %}" method="post" >
      {% csrf_token %}
      <div class="form-group">
      <input type="hidden" name="action" value="quit">
      <input type="hidden" name="next" value="{{request.path}}">
      <button type="submit" class="btn btn-danger btn-sm"  onclick="return confirm('You are about to kick {{user.username}}. Allright?')">
      {% bootstrap_icon "remove" %} Kick  !
      </button>
      </div>
      </form>
    </td>
</tr>
{% endfor %}
</tbody>
</table>
</div>

{% endblock %}
{% block extra_js %}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs/dt-1.10.16/datatables.min.css"/>
<script type="text/javascript" src="https://cdn.datatables.net/v/bs/dt-1.10.16/datatables.min.js"></script>
<script type="text/javascript">
$(document).ready(function() {
$('#user-table').DataTable();
} );
</script>
{% endblock %}